### ISSUE TITLE
Consider feature to include `--testsuite` as part of configuration file

### ISSUE THREAD

**Issue by mikeerickson** [spatie/phpunit-watcher#16]
It would sure be nice if we could include the `--testsuite` as part of the default execution.

```
watch:
  directories:
    - src
    - tests
  fileMask: '*.php'
  testSuites:
    - unit
    - feature
```
