### ISSUE TITLE
desktop notifications not working on OSX Mojave

### ISSUE THREAD

**Issue by vesper8** [spatie/phpunit-watcher#76]
I opened this issue already but figured I'd post here as well since you may know the answer

https://github.com/jolicode/JoliNotif/issues/57

this is the contents of my .phpunit-watcher.yml

```
watch:
  directories:
    - app
    - modules
    - tests
  fileMask: '*.php'
notifications:
  passingTests: true
  failingTests: true
phpunit:
  arguments: '--stop-on-failure'%
```

and I'm using iTerm on OSX Mojave
