### ISSUE TITLE
Error "Unable to set stream resource to non-blocking mode" In ReadableResourceStream.php line 56:

### ISSUE THREAD

**Issue by rogeriopradoj** [spatie/phpunit-watcher#82]
- Error output:
```shell
$ vendor/bin/phpunit-watcher watch


In ReadableResourceStream.php line 56:
                                                      
  Unable to set stream resource to non-blocking mode  
                                                      

watch [<phpunit-options>]
```
- S.O.:  Windows 10
- How I installed the package: `composer require spatie/phpunit-watcher --dev`
- Command (the result error is the same):
    - `vendor/bin/phpunit-watcher watch` (git-bash)
    - or `vendor\bin\phpunit-watcher watch` (cmd)
- Using a configuration file: yes, `.phpunit-watcher.yml`
- Content of configuration file:
```
watch:
  directories:
    - src
    - tests
  fileMask: '*.php'
notifications:
  passingTests: false
  failingTests: true
phpunit:
  binaryPath: vendor/bin/simple-phpunit
  arguments: '--testsuite unit'
```

References:

- https://github.com/reactphp/stream/issues/117
- https://github.com/clue/psocksd/commit/c2f2f90ffc8ebf8233839ba2f3553f2698930125
- https://github.com/reactphp/stream/blob/master/src/ReadableResourceStream.php#L56
https://github.com/reactphp/stream/pull/46
